### ISSUE TITLE
Ping not appearing properly 

### ISSUE THREAD

**Issue by Errorrist** [theGuildHall/pwnbox#12]
<img width="1680" alt="Screen Shot 2020-08-19 at 8 14 53 PM" src="https://user-images.githubusercontent.com/44757086/90702213-b6cb5600-e258-11ea-9f66-1b8cce7ab7d4.png">
<img width="575" alt="Screen Shot 2020-08-19 at 8 14 59 PM" src="https://user-images.githubusercontent.com/44757086/90702220-baf77380-e258-11ea-84a2-92c7726564fe.png">

Nice instructions, Can you help me fix this?

output of the vpnpanel.sh script are correct.
<img width="762" alt="Screen Shot 2020-08-19 at 8 17 04 PM" src="https://user-images.githubusercontent.com/44757086/90702331-f72ad400-e258-11ea-9aa1-cd1b7110be8f.png">

**Comment by theGuildHall** [comment]
Interesting issue.

Can you right click on the panel where your ping should be and select preferences? Might help to see what is there. Otherwise, if you haven't already, delete that panel and try it again.

**Comment by Colenk** [comment]
Same problem as that man. Tried deleting the panel it did nothing. And as for the preferences, they are just standard. ![image](https://user-images.githubusercontent.com/22532356/91002408-9541d580-e59c-11ea-87a6-370cf35f1aea.png)

I was messing around with the vpnpanel script and trying formatting it to see if it was an issue displaying the decimal number. 
I made it a float with a simple `printf "%.0f" and when using that as the echo instead I at least get the number 0 to show on the panel rather than nothing.
![image](https://user-images.githubusercontent.com/22532356/91002610-1f8a3980-e59d-11ea-91bc-6df93e158586.png)
![image](https://user-images.githubusercontent.com/22532356/91002598-1600d180-e59d-11ea-93c1-46a36d93bf9d.png)

Is there anything else you could think of for why only that part is not showing? If you have any ideas for me to test, I'll gladly take them. 

PS: My installation is stock from the guide other than a custom PS1 in my bashrc

**Comment by Colenk** [comment]
UPDATE: Found the fix for the problem from someones fork of the repo. Credit to @Flameeeeee for committing the fix in his fork.

@Errorrist You have to edit your vpnpanel.sh. 

Change `gwip=$(route -n | grep tun0 | grep UG | tr -s " " | cut -d " " -f 2)` to  `gwip=$(ip route | grep tun0 | grep via | cut -d " " -f 3)`

For some reason the "route -n" command doesnt return output properly, while "ip route" does.

@theGuildHall I suggest possibly updating the readme for others that have the issue, or possibly just changing the script within the repo. Big thanks.

**Comment by theGuildHall** [comment]
@Colenk glad you found the issue and how to fix it! I'll commit it now.

@Errorrist Please try it now! you can do a git pull or just copy the updated vpnpanel.sh
