### ISSUE TITLE
Pwnbox issue with theme

### ISSUE THREAD

**Issue by dimostenis21** [theGuildHall/pwnbox#6]
Hello , i just installed pwnbox , everything worked fine expect some thinks ... As you can see below missing lines on terminal and its not blue ,PS  i have tried again to copy paste the bashrc 

![ParrotSec-2020-07-03-17-12-21](https://user-images.githubusercontent.com/67795777/86482116-f9dd7280-bd59-11ea-9a15-be66fe707896.png)

**Comment by theGuildHall** [comment]
Hi there,
when you say it's not blue, are you referring to the terminal and the colors? If so, you need to go to "Edit -> Profile Preferences" in your terminal there. From there, you can adjust the transparency and the colors as well. The text color should be "#a4b1cd" and the background color should be "#141d2b". 

In fact, HTB just released their assets guide which includes the official color palette they use. (https://www.hackthebox.eu/docs/Hack_The_Box_Brand_Assets_Guide.pdf).

As for the missing lines, there are 2 terminal styles. The current one (which it looks like you are using) and the previous one, where there is a line wrap. If that's the one you are talking about, use the code below in your bashrc file:

```bash
PS1="\[\033[1;32m\]\342\224\200\$([[ \$(/opt/vpnbash.sh) == *\"10.\"* ]] && echo \"[\[\033[1;34m\]\$(/opt/vpnserver.sh)\[\033[1;32m\]]\342\224\200[\[\033[1;37m\]\$(/opt/vpnbash.sh)\[\033[1;32m\]]\342\224\200\")[\[\033[1;37m\]\u\[\033[01;32m\]@\[\033[01;34m\]\h\[\033[1;32m\]]\342\224\200[\[\033[1;37m\]\w\[\033[1;32m\]]\\$\[\e[0m\] "
```

Otherwise, if I misunderstood, please clarify

**Comment by dimostenis21** [comment]
Thank you so much 😊, keep up the good work!

**Comment by dimostenis21** [comment]
One more question, when im using tmux i don't have this customisation , can you help me? 🤤

**Comment by theGuildHall** [comment]
i haven't dug into the tmux config yet to see where the update needs to occur. I use terminator which works well. Good alternative if you aren't stuck to tmux.

**Comment by dimostenis21** [comment]
Thank you again , i still dont have this wrapped line but okay
